services:
  - type: web
    name: keru-main-api
    runtime: node
    plan: free
    region: ohio
    buildCommand: npm install --prefix backend
    startCommand: npm --prefix backend start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
